// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-RZyR2N9BkQHC8YdqGzAo7b4C483j09w',
    appId: '1:146077898154:web:2a5437b80fc1ccdd7cc7d3',
    messagingSenderId: '146077898154',
    projectId: 'todoey-flutter-9b078',
    authDomain: 'todoey-flutter-9b078.firebaseapp.com',
    storageBucket: 'todoey-flutter-9b078.appspot.com',
    measurementId: 'G-0Q4RS61N6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD335mkyzeZz5txJpcqGWOlvj9Sz5Azvwk',
    appId: '1:146077898154:android:5d7606e87d03056d7cc7d3',
    messagingSenderId: '146077898154',
    projectId: 'todoey-flutter-9b078',
    storageBucket: 'todoey-flutter-9b078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7puPsVFiVKZkFRuA8eBpnLRJMXiNuEys',
    appId: '1:146077898154:ios:5d009e1c19e7cf697cc7d3',
    messagingSenderId: '146077898154',
    projectId: 'todoey-flutter-9b078',
    storageBucket: 'todoey-flutter-9b078.appspot.com',
    iosClientId: '146077898154-d297ocu5lv70bj98r9u9qs5p28bk34ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoeyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7puPsVFiVKZkFRuA8eBpnLRJMXiNuEys',
    appId: '1:146077898154:ios:5d009e1c19e7cf697cc7d3',
    messagingSenderId: '146077898154',
    projectId: 'todoey-flutter-9b078',
    storageBucket: 'todoey-flutter-9b078.appspot.com',
    iosClientId: '146077898154-d297ocu5lv70bj98r9u9qs5p28bk34ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoeyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-RZyR2N9BkQHC8YdqGzAo7b4C483j09w',
    appId: '1:146077898154:web:530615a09c3c216f7cc7d3',
    messagingSenderId: '146077898154',
    projectId: 'todoey-flutter-9b078',
    authDomain: 'todoey-flutter-9b078.firebaseapp.com',
    storageBucket: 'todoey-flutter-9b078.appspot.com',
    measurementId: 'G-31DKKNHTMF',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA-RZyR2N9BkQHC8YdqGzAo7b4C483j09w',
    appId: '1:146077898154:web:eb51e12e93389e4d7cc7d3',
    messagingSenderId: '146077898154',
    projectId: 'todoey-flutter-9b078',
    authDomain: 'todoey-flutter-9b078.firebaseapp.com',
    storageBucket: 'todoey-flutter-9b078.appspot.com',
    measurementId: 'G-10FF5XWJ45',
  );
}
